apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-repo.yaml
  - cert-manager.yaml
  - longhorn-repo.yaml
  - longhorn.yaml
  - postgres-operator-repo.yaml
  - postgres-operator.yaml
  - https://github.com/hyperspike/gitea-operator/releases/download/v0.0.13/install.yaml
  - https://github.com/hyperspike/valkey-operator/releases/download/v0.0.61/install.yaml
  - gitea.yaml
