apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-repo.yaml
  - cert-manager.yaml
  - longhorn-repo.yaml
  - longhorn.yaml
  - postgres-operator-repo.yaml
  - postgres-operator.yaml
