apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This file is part of our "App-of-apps". See root-app.yaml
resources:
  # 1. Glob all YAML files ending in '-app.yaml' in the current directory ('apps/').
  #    This handles files like 'app-a-app.yaml' directly inside 'apps/'.
  - root-app.yaml
  - argocd-app.yaml
  - cert-manager-app.yaml
  - gitea-app.yaml
  - longhorn-app.yaml
  - dev-stacks-app.yaml
