apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-app.yaml
  - cert-manager-app.yaml
  - dev-stacks-app.yaml
  - gitea-app.yaml
  - longhorn-app.yaml
  - root-app.yaml

patches:
  - path: common/global-settings.patch.yaml
    target:
      kind: Application
  - path: common/patch-git-values.json6902.yaml
    target:
      kind: Application
    type: json6902  # This allows us to replace at a specific index in sources, namely the repo that holds our values
