apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-app.yaml
  - cert-manager-app.yaml
  - dev-stacks-app.yaml
  - gitea-app.yaml
  - longhorn-app.yaml
  - root-app.yaml

patches:
  - path: common/global-settings.patch.yaml
    target:
      kind: Application
  - path: common/patch-repo-url.yaml
    target:
      kind: Application
