persistence:
  # Sets Longhorn as the default StorageClass
  defaultClass: true
  # Required for single-node clusters
  defaultClassReplicaCount: 1

defaultSettings:
  defaultReplicaCount: 1
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/mnt/longhorn

csi:
  kubeletRootDir: /var/lib/kubelet
